shanti-uva/kmaps_engine

app/assets/javascripts/kmaps_engine/jquery.kmapstree.js, app/assets/javascripts/kmaps_engine/solr-utils.js
This branch fixes the error on the assets:precompile due to use of ES6 standard let
and Adds the option for the flyout kmapstree to sortChildren
=> Fix JavaScript for solr-utils and add sortChildren for kmapstree

app/views/features/_menu.html.erb
Fixes a bug that the %%ID%% pattern wasn't being added in the
features_path URL.
MANU-3446
=> Fixes bug on typeahead search on fly-out for Subjects

app/models/citation.rb, app/views/features/_feature.html.erb
An error occurs when an MMSIntegration citation was found and it didn't
contain any pages, the case was not being taken into account, that was
fixed and added some of the code for the citations to be displayed on
the _feature partial.
MANU-4932
=> Fix bibliographical reference for Online Resources

app/assets/javascripts/kmaps_engine/jquery.kmaps-typeahead.js, lib/kmaps_engine/version.rb
After fixing the search using Tibetan text an error was introduced, if
the text contained a space an invalid query was generated for Solr.
The fix is just a simple scape of spaces if they are found.
=> Fix fly-out search for text with spaces

app/controllers/admin/association_notes_controller.rb, lib/kmaps_engine/version.rb
The problem was on the redirect, there redirect was linking back to
feature and the router was assuming to use :id but feautres routes
assumes :fid to be the one comming from the URL request.
=> Fix bug when deleting a general note - MANU-4986

app/assets/javascripts/kmaps_engine/jquery.kmaps-typeahead.js, lib/kmaps_engine/version.rb
Commas were not being taken care on the fly-out search when cleaning up
special characters, now it is properly handle.
=> Add filter to handle commas in fly-out search - MANU-4046

app/controllers/admin/feature_names_controller.rb, lib/kmaps_engine/version.rb
There was an bug on feature_names_controller when the feature name was
destroyed it had a redirected to :back, but we should use redirect_back
and have a fallback ULR if the HTTP_REFERER is not present.
=> Fix FeatureName error when deleting - MANU 5085

app/helpers/application_helper.rb, lib/kmaps_engine/version.rb
Contextual_feature allows us to know which feature is the parent of the
current object, it wasn't taking into account objects that were of type:
feature_object_type now it does.
=> Added support for feature_object_type in contextual_feature - THLTOOLS-3587

app/assets/javascripts/kmaps_engine/jquery.kmapstree.js
Added support for sorting by field. Added two new options
sortNodes: [true|false]
sortNodesBy: <Field || default:header>
The field in sortNodesBy should be a field already included via the
Solr query, check the buildQuery function, and then on the node creation
function (createNode) and in the postProcess (this function runs after
the data for the fancy tree data has been loaded)to add that field into
each fancyTree node for use in the sorting function.
=> Add sorting by field for kmapsTree jQuery plugin - MANU-5137

app/views/public/_view_list.html.erb
There is a bug that is causing clicks to go through a stacked DOM
element to the elements behind. This is part of the solution, but it is
related to shanti_integration changes on the pointer events when the
menu is open or close.
=> Prevent click propagation for top menu click - MANU-5204

.github/PULL_REQUEST_TEMPLATE.md, app/assets/javascripts/kmaps_engine/flyout-kmaps-typeahead.js, app/assets/javascripts/kmaps_engine/jquery.kmaps-typeahead.js
**Jira issue**: MANU-5187
**Changes proposed in this pull request**:
Remove head letters from results
**Details of implementation**:
This was done by handling the filter parameter sent by the terms_engine and adding them to the filter query sent to solr.
When we are constructing the flyoutKmapsTypeahead, we can now use the filter option for example:
```javascript
$("#kmaps-explorer-search-term").flyoutKmapsTypeahead({
hostname: "<%= Feature.config.url %>",
hostname_assets: "<%= Flare.config.asset_url %>",
domain: '<%= Feature.uid_prefix %>',
filters_domain: '<%= Feature.uid_prefix %>',
filters: ["-associated_subjects:Letter"],
root_kmap_path: null,
features_path: "<%= (defined?(admin) && admin) ? admin_features_path : features_path %>/%%ID%%"
});
```
=> Remove letters from flyout search results - MANU-5187

app/assets/javascripts/kmaps_engine/jquery.kmapstree.js, app/assets/stylesheets/kmaps_engine/kmaps_typeahead.css.scss, lib/kmaps_engine/version.rb
**Jira issue:** MANU-5257
+ Add option for autoCollaps for KmapsTree
+ Add CSS to fix error on advanced search for Places
KmapsTree now supports the option for auto collapse, this is when one
node is selected if there is an open node it will close. The default
behaviour is false (no auto collapse), to set it on send true to the
option autoCollapse.
Example:
```ruby
$("#tree").kmapsTree({
termindex_root: "<%= Feature.config.url %>",
kmindex_root: "<%= MmsIntegration::Picture.config.url %>",
type: "<%= Feature.uid_prefix %>", //subjects
root_kmap_path: '',
baseUrl: "<%= (defined?(admin) && admin) ? admin_features_path : features_path %>/%%ID%%",
expand_path: "",
perspective: "<%= current_perspective.code %>", …
```
=> Add auto collapse option to KmapsTree and fix CSS for typeahead

app/assets/javascripts/kmaps_engine/kmaps-simple-typeahead.js, app/assets/javascripts/kmaps_engine/kmaps_relations_tree.js, app/assets/javascripts/kmaps_engine/kmaps_typeahead.js, app/assets/javascripts/kmaps_engine/solr-utils.js, app/controllers/admin/feature_names_controller.rb, app/controllers/preferences_controller.rb, app/views/admin/feature_names/prioritize.html.erb, vendor/assets/stylesheets/kmaps_typeahead/kmaps-typeahead.css
**Jira Issue:** MANU-5619, MANU-5623, MANU-5652
+ added a new implementation of the typeahead library that can be used in
simple forms to add the typeahead capability.
+ relations tree - added new support for marking nodes if they match certain
criteria, this criteria is added via predicates on the tree options and
now the tree supports adding additional fields to query.
+ fixed issues with prioritization of feature names.
+ removed unnecessary CSS
+ The new implementation of the simple typeahead, is as its name suggests, simple, it is not to be used as a complete replacement of the current implementation but as a small option when the queries are simple, new functionality can be added with time but the idea is …
=> Add new simple typeahead library and Updated Kmaps relations tree

app/assets/javascripts/kmaps_engine/kmaps_relations_tree.js, app/assets/javascripts/kmaps_engine/solr-utils.js, lib/kmaps_engine/version.rb
**Jira Issue:** MANU-5779
+ Add support on SolrUtils for views preferences for KmapsRelationsTree 
Now KmapsRelationsTree supports View preferences on the display of the
tree, if the view is not set it uses header by default.
=> Add support to SolrUtils for View for KmapsRelationsTree - MANU-5779

app/assets/javascripts/kmaps_engine/kmaps-simple-typeahead.js, app/assets/javascripts/kmaps_engine/kmaps_relations_tree.js, app/assets/javascripts/kmaps_engine/solr-utils.js, lib/kmaps_engine/version.rb
**Jira Issue:** MANU-6076
+ Fixed bug on Relations Tree when there was no predicate set for marking nodes.
+ Added functionality to Kmaps-simple-typeahead so we are able to update the additional filters setting.
+ Add new functionality to Relations Tree, to hide ancestors.
+ Add new functionality to Relations Tree, for marking all nodes.
+ Add Solr-utils capability to mark root nodes.
+ Add support for customAction, so a new action can be assigned to the nodes when activated.
There is a bug on Relations tree when a mark is not set for predicates,
which seldom happens but can trigger an error.
Add new functionality to Kmaps simple typeahead to support updating the
additional filters setting.
=> Fix bug on Relations Tree and Added simple typeahead update filter - MANU-6076

app/controllers/application_controller.rb, app/controllers/features_controller.rb, app/controllers/media_controller.rb, app/controllers/preferences_controller.rb, app/controllers/sessions_controller.rb, app/helpers/application_helper.rb, app/helpers/features_helper.rb, app/views/features/_search_results.html.erb, lib/kmaps_engine/session_manager.rb, lib/kmaps_engine/version.rb
**Jira Issue:** MANU-6102
+ Fix bug on `contextual_feature` accessing the sesison's `context_id`
The session sometimes accesses the `context_id` as a symbol and sometimes
as a string. This was fixed by supporting both cases.
Updated engine version for merge.
=> Fix bug on contextual_feature accessing session context - MANU-6102

app/assets/javascripts/kmaps_engine/essays_admin.js, app/assets/javascripts/kmaps_engine/kmaps-simple-typeahead.js, app/assets/javascripts/kmaps_engine/solr-utils.js, app/assets/stylesheets/kmaps_engine/application.css, app/assets/stylesheets/kmaps_engine/essays.css, app/controllers/admin/essays_controller.rb, app/models/essay.rb, app/models/feature.rb, app/models/language.rb, app/views/admin/essays/_form_fields.html.erb, app/views/admin/essays/_list.html.erb, app/views/admin/essays/edit.html.erb, app/views/admin/essays/index.html.erb, app/views/admin/essays/new.html.erb, app/views/admin/essays/show.html.erb, app/views/admin/features/show.html.erb, app/views/features/_feature.html.erb, config/initializers/assets.rb, config/locales/bo/models.yml, config/locales/dz/models.yml, config/locales/en/models.yml, config/locales/zh/models.yml, config/routes.rb, db/migrate/20200512175610_create_essays.rb, lib/kmaps_engine/version.rb
**Jira Issue:** MANU-6331
+ Add Essays to Editorial Interface
+ Display linked essay for Feature on view mode.
Previously we had Descriptions presented to the User as Essays, that was
supposed to be migrated to Mandala Texts. Now we are creating a new
Essay model that will be linked to Mandala Texts through
`ShantiIntegration`. This essays are going to be used to display a more
descriptive text for each Feature.
The Essay is tied up to the current Language. So a Feature could have
many Essays with different languages. When the Feature is displayed we
are going to show the Essay for the language currently selected by the
user in view mode.
=> Adds Mandala Texts Integration to Kmaps as Essays for each Feature - MANU-6331

app/views/admin/essays/_list.html.erb, app/views/features/_feature.html.erb, lib/kmaps_engine/version.rb
**Jira Issue:** MANU-6427
+ Add language column to Essays on the editorial interface.
+ Add a dropdown to display Mandala Home pages associated to different languages on user frontend.
Added a dropdown on the features user frontend when the features have an associated Essay(Mandala Hometext). We need to work on our frontend design. Currently is only a simple text and dropdown.
=> Adds Hometext language selector on frontend - MANU-6427

app/assets/stylesheets/kmaps_engine/application.css, app/helpers/application_helper.rb, app/models/feature_name.rb, lib/kmaps_engine/version.rb
**Jira Issue:** MANU-6250
+ Added class "non-capitalizable" in link and span of breadcrumbs for css rendering
+ Determined if that a name is non capitalizable when it is an orthographic transliteration of another name (for example tibetan wylie)
Certain names should be and certain names should not be capitalized in breadcrumbs. This applies to subjects, places and terms. To calculate which, a method was added to feature_name model and used within helpers involved in breadcrumb generation.
=> Fixed capitalization of names in breadcrumbs in view and edit mode

app/helpers/admin_helper.rb, app/views/admin/feature_names/_feature_names.html.erb, app/views/admin/feature_relations/_list.html.erb
MANU-7776 (https://uvaissues.atlassian.net/browse/MANU-7776)
Currently, in the accordion under some sections (TERM RELATIONS and NAMES sections),
there are tables that have four columns as follows:
Notes | Add Note | Dates | Add Dates
Combine the data **Notes** and **Add Note** under one heading "**Notes**" in one column
Combine the data **Dates** and **Add Date** under one heading "**Dates**" in one column
This change was requested via this document:
https://docs.google.com/document/d/1TwkQ02IK7vM_7wfq6ZoNZeyMbDZxOxzP16VvNIHuJHs/edit
=> MANU-7776 combine notes/dates columns

app/views/admin/captions/_list.html.erb, app/views/admin/descriptions/_descriptions_list.html.erb, app/views/admin/essays/_list.html.erb, app/views/admin/feature_geo_codes/_list.html.erb, app/views/admin/feature_relation_types/_list.html.erb, app/views/admin/feature_relations/_list.html.erb, app/views/admin/illustrations/_list.html.erb, app/views/admin/summaries/_list.html.erb
**MANU-7789** https://uvaissues.atlassian.net/browse/MANU-7789
+ fixes issue where each accordion section output "No Terms found" instead of "No (section name) found"
Please merge and deploy the corresponding TERMS_ENGINE pull request at the same time as this one:
https://github.com/shanti-uva/terms_engine/pull/75
Changes were requested in this doc: https://docs.google.com/document/d/1TwkQ02IK7vM_7wfq6ZoNZeyMbDZxOxzP16VvNIHuJHs/edit
=> MANU-7789 show appropriate section name in empty collection message

app/assets/javascripts/kmaps_engine/descriptions_admin_accordion.js, app/helpers/admin_helper.rb, app/views/admin/affiliations/edit.html.erb, app/views/admin/affiliations/new.html.erb, app/views/admin/affiliations/show.html.erb, app/views/admin/citations/_breadcrumbs.html.erb, app/views/admin/citations/show.html.erb, app/views/admin/descriptions/edit.html.erb, app/views/admin/descriptions/new.html.erb, app/views/admin/descriptions/show.html.erb, app/views/admin/feature_names/index.html.erb, app/views/admin/feature_names/prioritize.html.erb, app/views/admin/notes/_breadcrumbs.html.erb, app/views/admin/notes/edit.html.erb, app/views/admin/notes/new.html.erb, app/views/admin/notes/show.html.erb, config/initializers/assets.rb
https://uvaissues.atlassian.net/browse/MANU-7821
* Improve breadcrumb nav. Sometimes it links to irrelevant and/or "dead end" pages that are confusing for users.
There are a few commits from other tickets: 7873 (but this ticket should not be moved into TESTING yet - needs more work)
and MANU-7777 which is already in TESTING and doesn't need to be moved.
=> MANU-7891 breadcrumb nav improvements (WIP)

app/helpers/admin_helper.rb
https://uvaissues.atlassian.net/browse/MANU-7792
* removes HOME link from breadcrumbs as it loads the admin layout with no content, which does not provide any utility.
=> MANU-7929 Removes HOME link from breadcrumbs

app/helpers/admin_helper.rb
Removing with css in terms app only instead. 
**MANU-7929** https://uvaissues.atlassian.net/browse/MANU-7929
**MANU-7891** https://uvaissues.atlassian.net/browse/MANU-7891
This reverts the change that removed the HOME link from the breadcrumbs ordered list.
We will remove it in the terms_engine code instead.
=> Reverts removing HOME from breadcrumbs

app/views/admin/notes/_breadcrumbs.html.erb
https://uvaissues.atlassian.net/browse/MANU-7939
This change was made in service of the above ticket but really just changes how we handle breadcrumbs for deeper nested notes. If the note.notable responds to context, link the breadcrumb to that. Otherwise use the note's feature.
=> MANU-7939 adding NOTES admin to passage translations, passages, etymologies and definitions in Terms
